services:
  - type: web
    name: edgelab
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: CF_ACCOUNT_ID
        sync: false
      - key: CF_API_TOKEN
        sync: false
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
